# @format

version: 2.1

aliases:
  - &defaults
    working_directory: ~/repos
    docker:
      - image: circleci/node:12.21.0

  - &test_tag_filter
    filters:
      tags:
        ignore: /.*/

  - &canary_tag_filter
    filters:
      tags:
        only: /^v[\d\.]+-(canary|alpha|beta)\.\d$/
      branches:
        ignore: /.*/

  - &prod_tag_filter
    filters:
      tags:
        only: /^v[\d\.]+$/
      branches:
        ignore: /.*/

  - &attach
    attach_workspace:
      at: ~/repos
  - &auth_registry
    run:
      name: Authenticate with registry
      command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repos/.npmrc
  - &save_package_informations
    run:
      name: Save package informations
      command: |
        echo 'export CURRENT_PACKAGE_VERSION=$(git describe --tags)' >> $BASH_ENV
        echo 'export CURRENT_PACKAGE_NAME=$(jq ".name" ~/repos/package.json -r)' >> $BASH_ENV
  - &versioning_package
    run:
      name: Versioning package
      command: npm version $CURRENT_PACKAGE_VERSION --no-git-tag-version
  - &print_informations
    run:
      name: Print package informations
      command: echo $CURRENT_PACKAGE_NAME@$CURRENT_PACKAGE_VERSION
  - &persist
    persist_to_workspace:
      root: ~/repos
      paths:
        - .

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - *persist

  build-all:
    <<: *defaults
    steps:
      - *attach
      - run:
          name: Run build
          command: yarn build:ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - *persist

  tests-package-proxy:
    <<: *defaults
    steps:
      - *attach
      - run:
          name: Run tests
          command: yarn workspace package-proxy run test:ci
      - store_artifacts:
          path: packages/package-proxy/coverage/lcov-report
      - run:
          name: Report coverage
          command: yarn workspace package-proxy run test:report

  tests-package-consumer:
    <<: *defaults
    steps:
      - *attach
      - run:
          name: Run tests
          command: yarn workspace package-proxy run test:ci
      - store_artifacts:
          path: packages/package-proxy/coverage/lcov-report
      - run:
          name: Report coverage
          command: yarn workspace package-proxy run test:report

  publish-canary:
    <<: *defaults
    steps:
      - *attach
      - *auth_registry
      - *save_package_informations
      - *versioning_package
      - *print_informations
      - run:
          name: Publish package
          command: npm publish --access public --tag canary
      - *persist

  publish:
    <<: *defaults
    steps:
      - *attach
      - *auth_registry
      - *save_package_informations
      - *versioning_package
      - *print_informations
      - run:
          name: Publish package
          command: npm publish --access public
      - *persist

workflows:
  version: 2
  integration:
    jobs:
      - install:
          <<: *test_tag_filter
      - build-all:
          <<: *test_tag_filter
          requires:
            - install
      - tests-package-proxy:
          <<: *test_tag_filter
          requires:
            - install
      - tests-package-consumer:
          <<: *test_tag_filter
          requires:
            - build-all

  publish-canary:
    jobs:
      - install:
          <<: *prod_tag_filter
      - tests-package-proxy:
          <<: *canary_tag_filter
          requires:
            - install
      - build-all:
          <<: *canary_tag_filter
          requires:
            - install
      - tests-package-consumer:
          <<: *canary_tag_filter
          requires:
            - build-all
      - require-publish:
          type: approval
          requires:
            - tests-package-proxy
            - build-all
            - tests-package-consumer
          <<: *canary_tag_filter
      - publish-canary:
          context: personal_packages_vars
          requires:
            - require-publish
          <<: *canary_tag_filter

  publish:
    jobs:
      - install:
          <<: *prod_tag_filter
      - build-all:
          <<: *prod_tag_filter
          requires:
            - install
      - tests-package-proxy:
          <<: *prod_tag_filter
          requires:
            - install
      - tests-package-proxy:
          <<: *prod_tag_filter
          requires:
            - install
      - require-publish:
          type: approval
          requires:
            - tests-package-proxy
            - build-all
            - tests-package-consumer
          <<: *prod_tag_filter
      - publish:
          context: personal_packages_vars
          requires:
            - require-publish
          <<: *prod_tag_filter
